# Generated by Django 4.2.2 on 2023-06-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=50, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('completed_by', models.DateField(null=True)),
            ],
        ),
    ]
