# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='complete',
            field=models.CharField(default='checked', max_length=12),
        ),
    ]
